configfile: "../config/config.yaml"

import pandas as pd
from pathlib import Path

wildcard_constraints:
    eid='[^.]+',
    mark='[^.]+',

genome = config["genome"]
hg_sizes = config["paths"]["genome_sizes"]

tissue_mapping = pd.read_csv('annotations/tissue_mapping.csv')
eid2tissue = {r.eid:r.tissue for r in tissue_mapping.to_records()}

eids = config["eids"]
marks = (config["marks"]["core"] + (config["marks"]["extra"] if config.get("use_extra", False) else []))
tissues = [eid2tissue[eid] for eid in eids]

# 目标产物
tagalign = expand('hist/{eid}-{mark}.tagAlign', eid=eids, mark=marks)
bam = expand('hist/{eid}-{mark}.sorted.bam', eid=eids, mark=marks)
bai = expand('hist/{eid}-{mark}.sorted.bam.bai', eid=eids, mark=marks)
bedgraph = expand('hist/{eid}-{mark}.sorted.bedGraph', eid=eids, mark=marks)
bigwig = expand('hist/{eid}-{mark}.bw', eid=eids, mark=marks)
raw_exp = 'exp/raw_exp.tsv'
train_meta = 'train.csv'
signals = expand('data/{eid}/.done', eid=eids)

ALL = []
ALL += bigwig
ALL += [raw_exp, train_meta]
ALL += signals

rule all:
    input: ALL

# 1) 下载 Roadmap tagAlign
rule download_chip_tagalign:
    output: 'hist/{eid}-{mark}.tagAlign'
    resources: network=1
    conda: 'environment.yaml'
    benchmark: 'benchmarks/download_chip_tagalign/{eid}-{mark}.tsv'
    shell:
        'wget "https://egg2.wustl.edu/roadmap/data/byFileType/alignments/consolidated/{wildcards.eid}-{wildcards.mark}.tagAlign.gz" -O- | gunzip -c > {output}'

# 2) tagAlign -> BAM
rule bedtobam:
    input: 'hist/{eid}-{mark}.tagAlign'
    output: 'hist/{eid}-{mark}.bam'
    conda: 'environment.yaml'
    benchmark: 'benchmarks/bedtobam/{eid}-{mark}.tsv'
    shell:
        'bedtools bedtobam -i {input} -g {hg_sizes} > {output}'

rule sambamba_sort:
    input: 'hist/{eid}-{mark}.bam'
    output: 'hist/{eid}-{mark}.sorted.bam'
    threads: 4
    conda: 'environment.yaml'
    benchmark: 'benchmarks/sambamba_sort/{eid}-{mark}.tsv'
    shell:
        'sambamba sort -o {output} -t {threads} --tmpdir . {input}'

rule sambamba_index:
    input: 'hist/{eid}-{mark}.sorted.bam'
    output: 'hist/{eid}-{mark}.sorted.bam.bai'
    threads: 4
    conda: 'environment.yaml'
    benchmark: 'benchmarks/sambamba_index/{eid}-{mark}.tsv'
    shell:
        'sambamba index -t {threads} {input}'

# 3) BAM -> bedGraph（覆盖深度）
rule bedtools_genomecov:
    input:
        bam='hist/{eid}-{mark}.sorted.bam',
        bai='hist/{eid}-{mark}.sorted.bam.bai'
    output: 'hist/{eid}-{mark}.sorted.bedGraph'
    conda: 'environment.yaml'
    benchmark: 'benchmarks/bedtools_genomecov/{eid}-{mark}.tsv'
    shell:
        'bedtools genomecov -ibam {input.bam} -bga | bedtools sort -i stdin > {output}'

# 4) bedGraph -> bigWig（便于随机访问切片）
rule bedgraph_to_bigwig:
    input:
        bdg='hist/{eid}-{mark}.sorted.bedGraph'
    output:
        'hist/{eid}-{mark}.bw'
    conda: 'environment.yaml'
    benchmark: 'benchmarks/bedgraph_to_bigwig/{eid}-{mark}.tsv'
    shell:
        'bedGraphToBigWig {input.bdg} {hg_sizes} {output}'

# 表达矩阵
rule download_exp:
    output: 'exp/raw_exp.tsv'
    conda: 'environment.yaml'
    benchmark: 'benchmarks/download_exp.tsv'
    shell:
        'wget https://egg2.wustl.edu/roadmap/data/byDataType/rna/expression/57epigenomes.RPKM.pc.gz -O- | '
        'gunzip -c | sed \'s/[ \\t]*$//\' > {output}'

# （保留现有元数据下载，若仍需）
rule prepare_train_metadata:
    input:
        expand('annotations/{tissue}_frag2neighbors.pickle', tissue=tissues),
        expand('annotations/{tissue}_pair2score.pickle', tissue=tissues)
    output: 'train.csv'
    conda: 'environment.yaml'
    benchmark: 'benchmarks/prepare_train_metadata.tsv'
    shell: 'python scripts/prepare_train_metadata.py'

rule download_frag2neighbors_per_tissue:
    output: 'annotations/{tissue}_frag2neighbors.pickle'
    resources: network=1
    benchmark: 'benchmarks/download_frag2neighbors_per_tissue/{tissue}.tsv'
    shell:
        'wget https://dohlee-bioinfo.sgp1.digitaloceanspaces.com/chromoformer-data/{wildcards.tissue}_frag2neighbors.pickle -O- > {output}'

rule download_pair2score_per_tissue:
    output: 'annotations/{tissue}_pair2score.pickle'
    resources: network=1
    benchmark: 'benchmarks/download_pair2score_per_tissue/{tissue}.tsv'
    shell:
        'wget https://dohlee-bioinfo.sgp1.digitaloceanspaces.com/chromoformer-data/{wildcards.tissue}_pair2score.pickle -O- > {output}'

# 从 bigWig 提取信号用于后续 Dataset 在线切片，这里保持 .done 标记
rule extract_signals:
    input:
        train='train.csv',
        bigwigs=expand('hist/{{eid}}-{mark}.bw', mark=marks)
    output:
        touch('data/{eid}/.done')
    benchmark: 'benchmarks/extract_signals/{eid}.tsv'
    shell:
        'echo "OK" > /dev/null'
